apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
        - name: agent-service
          image: phuongnbp/agent-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_URL
              value: redis://192.168.1.165:6379/0 # ipconfig
            - name: SCHEDULE_SERVICE_URL
              value: http://192.168.1.165:8080  # ipconfig